name: Publish to RubyGems

on:
  workflow_dispatch:
  push:
    tags:
      - v*
  pull_request:
    branches: [main, master]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true

      - name: Run tests
        run: bundle exec rspec spec --format progress

  build:
    name: Build Ruby gem
    needs: test
    if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment: release
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{github.ref_name}}

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Build gem
        run: |
          gem build lara-sdk.gemspec

      - name: Publish gem
        run: |
          gem push lara-sdk-*.gem
        env:
          GEM_HOST_API_KEY: oidc-${{ github.repository_owner }}